// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun May 18 19:17:44 2014

MUX MUX_inst
(
	.S(S_sig) ,	// input  S_sig
	.A(A_sig) ,	// input [3]:[3]] A_sig
	.A(A_sig) ,	// input [2]:[2]] A_sig
	.A(A_sig) ,	// input [1]:[1]] A_sig
	.A(A_sig) ,	// input [0]:[0]] A_sig
	.B(B_sig) ,	// input [3]:[3]] B_sig
	.B(B_sig) ,	// input [2]:[2]] B_sig
	.B(B_sig) ,	// input [1]:[1]] B_sig
	.B(B_sig) ,	// input [0]:[0]] B_sig
	.Z(Z_sig) ,	// output [3]:[3]] Z_sig
	.Z(Z_sig) ,	// output [2]:[2]] Z_sig
	.Z(Z_sig) ,	// output [1]:[1]] Z_sig
	.Z(Z_sig) 	// output [0]:[0]] Z_sig
);

