// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun May 18 19:11:25 2014

PC PC_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.PC(PC_sig) ,	// input [3]:C[3]] PC_sig
	.PC(PC_sig) ,	// input [2]:C[2]] PC_sig
	.PC(PC_sig) ,	// input [1]:C[1]] PC_sig
	.PC(PC_sig) ,	// input [0]:C[0]] PC_sig
	.addr(addr_sig) ,	// output [3]:ddr[3]] addr_sig
	.addr(addr_sig) ,	// output [2]:ddr[2]] addr_sig
	.addr(addr_sig) ,	// output [1]:ddr[1]] addr_sig
	.addr(addr_sig) 	// output [0]:ddr[0]] addr_sig
);

